# Generated by Django 5.2.4 on 2025-07-21 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('captain_name', models.CharField(help_text='Name of the team captain.', max_length=255)),
                ('team_members', models.JSONField(default=list, help_text="List of team members' names.")),
                ('captain_phone', models.CharField(help_text='Phone number of the team captain.', max_length=20)),
                ('captain_email', models.EmailField(help_text='Email address of the team captain.', max_length=254)),
                ('project_topic', models.TextField(help_text='Topic or description of the project.')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp of submission.')),
            ],
            options={
                'verbose_name': 'Project Submission',
                'verbose_name_plural': 'Project Submissions',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
