# Generated by Django 5.2.4 on 2025-08-08 05:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MainEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('event_id', models.CharField(blank=True, editable=False, max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('event_id', models.CharField(blank=True, editable=False, max_length=100, unique=True)),
                ('parent_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subevents', to='events.mainevent')),
            ],
        ),
        migrations.CreateModel(
            name='SubSubEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('rules', models.TextField(blank=True, null=True)),
                ('minTeamSize', models.PositiveIntegerField(default=1)),
                ('maxTeamSize', models.PositiveIntegerField(default=1)),
                ('minFemaleParticipants', models.PositiveIntegerField(default=0)),
                ('isFacultyMentorRequired', models.BooleanField(default=False)),
                ('event_id', models.CharField(blank=True, editable=False, max_length=100, unique=True)),
                ('parent_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subsubevents', to='events.mainevent')),
                ('parent_subevent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subsubevents', to='events.subevent')),
            ],
        ),
    ]
