# Generated by Django 5.2.4 on 2025-08-18 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainevent',
            name='isOpen',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name='subevent',
            name='isOpen',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name='subsubevent',
            name='isOpen',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
