version: '3.8'

services:
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=satchi
      - POSTGRES_USER=satchi
      - POSTGRES_PASSWORD=satchipass

  backend:
    build:
      context: ./satchi_api
      dockerfile: Dockerfile
    command: gunicorn backend.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./satchi_api:/app
    ports:
      - "8000:8000"
    environment:
      - DJANGO_DEBUG=True
      - DJANGO_SECRET_KEY=change_me_in_prod
      - DJANGO_ALLOWED_HOSTS=localhost,127.0.0.1,backend
      - DJANGO_CORS_ALLOWED_ORIGINS=http://localhost,http://127.0.0.1,http://localhost:5173
      - DATABASE_URL=postgres://satchi:satchipass@db:5432/satchi
    depends_on:
      - db

  frontend:
    build:
      context: ./satchi-main
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  postgres_data:
