# Generated by Django 5.2.4 on 2025-08-08 05:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
        ('users', '0002_user_course_user_current_year_user_degree_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('PARTICIPANT', 'Participant'), ('SUPERADMIN', 'Super Admin'), ('EVENTADMIN', 'Event Admin'), ('SUBEVENTADMIN', 'Sub Event Admin'), ('EVENTMANAGER', 'Event Manager'), ('SUBEVENTMANAGER', 'Sub Event Manager'), ('SUBSUBEVENTMANAGER', 'Sub Sub Event Manager'), ('COORDINATOR', 'Coordinator')], default='PARTICIPANT', max_length=20),
        ),
        migrations.CreateModel(
            name='EventUserMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_role', models.CharField(choices=[('PARTICIPANT', 'Participant'), ('SUPERADMIN', 'Super Admin'), ('EVENTADMIN', 'Event Admin'), ('SUBEVENTADMIN', 'Sub Event Admin'), ('EVENTMANAGER', 'Event Manager'), ('SUBEVENTMANAGER', 'Sub Event Manager'), ('SUBSUBEVENTMANAGER', 'Sub Sub Event Manager'), ('COORDINATOR', 'Coordinator')], default='PARTICIPANT', max_length=20)),
                ('main_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_users', to='events.mainevent')),
                ('sub_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_users', to='events.subevent')),
                ('sub_sub_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_users', to='events.subsubevent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
