# Generated by Django 4.2.23 on 2025-07-21 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('captain_name', models.CharField(max_length=100)),
                ('team_members', models.JSONField()),
                ('captain_phone', models.CharField(max_length=20)),
                ('captain_email', models.EmailField(max_length=254)),
                ('project_topic', models.TextField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
