# Generated by Django 5.2.4 on 2025-09-10 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_projectsubmission_project'),
        ('events', '0002_mainevent_isopen_subevent_isopen_subsubevent_isopen'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='events.subsubevent'),
        ),
        migrations.AddField(
            model_name='project',
            name='faculty_mentor_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='team_name',
            field=models.CharField(default='def', max_length=100),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='api.project')),
            ],
        ),
    ]
